#!/usr/bin/env bash
# build-rust.sh — Xcode Build Phase から呼ばれる Rust ビルドスクリプト
#
# Xcode の Build Phases → Run Script で以下のように設定:
#   ${PROJECT_DIR}/scripts/build-rust.sh

set -euo pipefail

# Xcode のビルド環境では ~/.cargo/bin が PATH に含まれないことがある
source "$HOME/.cargo/env" 2>/dev/null || export PATH="$HOME/.cargo/bin:$PATH"

# プロジェクトルート（モノレポのルート）
REPO_ROOT="$(cd "$(dirname "$0")/../../../" && pwd)"
FFI_CRATE="${REPO_ROOT}/crates/cplp-ffi"

echo "==> Building cplp-ffi (${CONFIGURATION:-Debug})"

# Rust ターゲットを Xcode の ARCHS から決定
case "${ARCHS:-arm64}" in
    arm64)  RUST_TARGET="aarch64-apple-darwin" ;;
    x86_64) RUST_TARGET="x86_64-apple-darwin" ;;
    *)      RUST_TARGET="aarch64-apple-darwin" ;;
esac

# Release / Debug 判定
if [ "${CONFIGURATION:-Debug}" = "Release" ]; then
    CARGO_FLAGS="--release"
    CARGO_OUT_DIR="${REPO_ROOT}/target/${RUST_TARGET}/release"
else
    CARGO_FLAGS=""
    CARGO_OUT_DIR="${REPO_ROOT}/target/${RUST_TARGET}/debug"
fi

# cargo ビルド
cargo build -p cplp-ffi ${CARGO_FLAGS} --target "${RUST_TARGET}"

# 生成物の存在確認（サイレント失敗を防ぐ）
DEST="${BUILT_PRODUCTS_DIR:-${REPO_ROOT}/target/ffi-out}"
mkdir -p "${DEST}"

# dylib コピー（必須）
cp "${CARGO_OUT_DIR}/libcplp_ffi.dylib" "${DEST}/"

# staticlib コピー（オプション — visionOS 向け）
cp "${CARGO_OUT_DIR}/libcplp_ffi.a" "${DEST}/" 2>/dev/null || true

# ヘッダーコピー（必須 — Bridging Header が参照）
if [ ! -f "${FFI_CRATE}/cplp_ffi.h" ]; then
    echo "ERROR: cplp_ffi.h not generated by cargo build (cbindgen failure?)"
    exit 1
fi
cp "${FFI_CRATE}/cplp_ffi.h" "${DEST}/"

# install_name を @rpath に変更（.app バンドル内からの解決に必要）
install_name_tool -id "@rpath/libcplp_ffi.dylib" "${DEST}/libcplp_ffi.dylib"

# --- dylib のアドホック署名 ---
# Hardened Runtime 有効時、署名なしの dylib はロード時に SIGKILL される。
# Xcode が .app 全体を署名する前に、dylib 単体にも署名が必要。
# CI / ローカルで CPLP_CODESIGN_IDENTITY を設定すれば正式な署名を使用。
SIGN_IDENTITY="${CPLP_CODESIGN_IDENTITY:-"-"}"
codesign --force --sign "${SIGN_IDENTITY}" \
    --timestamp \
    --options runtime \
    "${DEST}/libcplp_ffi.dylib"
echo "==> dylib signed (identity: ${SIGN_IDENTITY})"

# --- notarytool による公証手順（リリース時に手動実行） ---
# 1. .app をビルド（Archive → Export）
#    xcodebuild archive -scheme CplpMac -archivePath build/CplpMac.xcarchive
#    xcodebuild -exportArchive -archivePath build/CplpMac.xcarchive \
#               -exportPath build/export -exportOptionsPlist ExportOptions.plist
#
# 2. zip 化
#    ditto -c -k --keepParent "build/export/CPLP Sound System.app" build/CplpMac.zip
#
# 3. 公証に提出
#    xcrun notarytool submit build/CplpMac.zip \
#        --apple-id "$APPLE_ID" \
#        --team-id "$TEAM_ID" \
#        --password "$APP_SPECIFIC_PASSWORD" \
#        --wait
#
# 4. staple（公証チケットを .app に埋め込む）
#    xcrun stapler staple "build/export/CPLP Sound System.app"
#
# 5. 検証
#    spctl --assess --type execute --verbose=4 "build/export/CPLP Sound System.app"

echo "==> cplp-ffi build complete → ${DEST}"
