/* cplp-ffi — auto-generated by cbindgen. DO NOT EDIT. */

#ifndef CPLP_FFI_H
#define CPLP_FFI_H

/* Warning: this file is auto-generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * FFI 結果コード
 */
typedef enum CplpResult {
    /**
     * 成功
     */
    CPLP_RESULT_OK = 0,
    /**
     * 初期化エラー
     */
    CPLP_RESULT_INIT_ERROR = 1,
    /**
     * 無効な引数
     */
    CPLP_RESULT_INVALID_ARGUMENT = 2,
    /**
     * ランタイムが未初期化
     */
    CPLP_RESULT_NOT_INITIALIZED = 3,
    /**
     * オーディオエンジンエラー
     */
    CPLP_RESULT_AUDIO_ERROR = 10,
    /**
     * セッションエラー
     */
    CPLP_RESULT_SESSION_ERROR = 20,
    /**
     * 内部エラー
     */
    CPLP_RESULT_INTERNAL_ERROR = 99,
} CplpResult;

/**
 * セッション接続状態
 */
typedef enum CplpSessionStatus {
    /**
     * 未接続
     */
    CPLP_SESSION_STATUS_DISCONNECTED = 0,
    /**
     * 接続中
     */
    CPLP_SESSION_STATUS_CONNECTING = 1,
    /**
     * 接続済み
     */
    CPLP_SESSION_STATUS_CONNECTED = 2,
    /**
     * 切断中
     */
    CPLP_SESSION_STATUS_DISCONNECTING = 3,
} CplpSessionStatus;

/**
 * FFI バージョン情報
 */
typedef struct CplpVersion {
    uint32_t major;
    uint32_t minor;
    uint32_t patch;
} CplpVersion;

/**
 * ステレオメーター値（FFI 転送用）
 */
typedef struct CplpAudioMeters {
    float left;
    float right;
} CplpAudioMeters;

/**
 * プラグインスキャン結果（1 件分）
 */
typedef struct CplpPluginInfo {
    /**
     * プラグイン ID（C 文字列、呼び出し側で free 不要）
     */
    const char *id;
    /**
     * プラグイン名（C 文字列）
     */
    const char *name;
} CplpPluginInfo;

/**
 * プラグインスキャン結果リスト
 */
typedef struct CplpPluginList {
    struct CplpPluginInfo *items;
    uint32_t count;
} CplpPluginList;

/**
 * 1 トラックの状態（C 構造体）
 */
typedef struct CplpTrackInfo {
    /**
     * ピア ID（C 文字列）
     */
    const char *peer_id;
    /**
     * ラベル（C 文字列）
     */
    const char *label;
    /**
     * ボリューム（0.0–1.0）
     */
    float volume;
    /**
     * パン（-1.0=L, 0.0=C, 1.0=R）
     */
    float pan;
    /**
     * ミュート
     */
    bool mute;
    /**
     * ソロ
     */
    bool solo;
} CplpTrackInfo;

/**
 * ミキサー状態（トラック一覧 + マスター）
 */
typedef struct CplpMixerState {
    /**
     * トラック配列
     */
    struct CplpTrackInfo *tracks;
    /**
     * トラック数
     */
    uint32_t track_count;
    /**
     * マスターボリューム（0.0–1.0）
     */
    float master_volume;
} CplpMixerState;

/**
 * セッション状態（C 構造体）
 */
typedef struct CplpSessionState {
    /**
     * 接続状態
     */
    enum CplpSessionStatus status;
    /**
     * 接続中のピア数（自分を含む）
     */
    uint32_t peer_count;
    /**
     * ロビー URL（C 文字列。Disconnected のときは null）
     */
    const char *lobby_url;
} CplpSessionState;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * ランタイムを初期化する
 *
 * アプリ起動時に一度だけ呼ぶこと。二重初期化はエラーを返す。
 */
enum CplpResult cplp_init(void);

/**
 * ランタイムを破棄する
 *
 * アプリ終了時に呼ぶこと。Arc の参照カウントが 0 になった時点で実際に解放される。
 */
enum CplpResult cplp_destroy(void);

/**
 * バージョン情報を取得
 */
struct CplpVersion cplp_version(void);

/**
 * オーディオエンジンを開始（デフォルト設定でサイン波テスト出力）
 */
enum CplpResult cplp_audio_start(void);

/**
 * オーディオエンジンを停止
 */
enum CplpResult cplp_audio_stop(void);

/**
 * メーター値を取得（lock-free ポーリング）
 */
struct CplpAudioMeters cplp_audio_get_meters(void);

/**
 * オーディオが実行中かどうか
 */
bool cplp_audio_is_running(void);

/**
 * CLAP プラグインをスキャン
 *
 * 戻り値のリストは `cplp_plugin_list_free` で解放すること。
 */
struct CplpPluginList cplp_audio_scan_plugins(void);

/**
 * プラグインリストを解放
 *
 * # Safety
 * `cplp_audio_scan_plugins` で返されたリストのみ渡すこと。
 */
void cplp_plugin_list_free(struct CplpPluginList list);

/**
 * 最後のエラーメッセージを取得する（C 文字列ポインタ）
 *
 * # Safety
 * 返されたポインタは次の FFI 呼び出しまで有効。呼び出し側で free してはいけない。
 * CString は thread_local に保持されるため、同一スレッド上の次の set_error
 * 呼び出しまでポインタは安全。
 */
const char *cplp_last_error(void);

/**
 * トラックのボリュームを設定
 *
 * # Safety
 * `peer_id` は有効な null 終端 C 文字列であること。
 */
enum CplpResult cplp_mixer_set_volume(const char *peer_id, float volume);

/**
 * トラックのパンを設定
 *
 * # Safety
 * `peer_id` は有効な null 終端 C 文字列であること。
 */
enum CplpResult cplp_mixer_set_pan(const char *peer_id, float pan);

/**
 * トラックのミュートを設定
 *
 * # Safety
 * `peer_id` は有効な null 終端 C 文字列であること。
 */
enum CplpResult cplp_mixer_set_mute(const char *peer_id, bool mute);

/**
 * ミキサー状態を取得
 *
 * 戻り値は `cplp_mixer_state_free` で解放すること。
 */
struct CplpMixerState cplp_mixer_get_state(void);

/**
 * ミキサー状態を解放
 *
 * # Safety
 * `cplp_mixer_get_state` で返された値のみ渡すこと。
 */
void cplp_mixer_state_free(struct CplpMixerState state);

/**
 * CAMetalLayer をアタッチして 3D シーン描画を開始
 *
 * # Safety
 * `metal_layer` は有効な `CAMetalLayer` ポインタであること。
 */
enum CplpResult cplp_scene_attach(void *metal_layer, uint32_t width, uint32_t height);

/**
 * シーンをデタッチ
 *
 * RwLock 内の Arc を None にする。既存の render/resize が Arc を保持していれば
 * 最後の Arc がドロップされるまで SceneState は生存する（UAF 不可能）。
 */
enum CplpResult cplp_scene_detach(void);

/**
 * リサイズ
 */
enum CplpResult cplp_scene_resize(uint32_t width, uint32_t height);

/**
 * 1 フレーム描画（DisplayLink から呼ばれる）
 */
enum CplpResult cplp_scene_render(void);

/**
 * セッションに接続
 *
 * # Safety
 * `lobby_url` は有効な null 終端 C 文字列であること。
 */
enum CplpResult cplp_session_connect(const char *lobby_url);

/**
 * セッションから切断
 */
enum CplpResult cplp_session_disconnect(void);

/**
 * セッション状態を取得
 *
 * 返される `CplpSessionState` 内の `lobby_url` ポインタは、
 * 同一スレッド上の次の FFI 呼び出しまで有効。
 */
struct CplpSessionState cplp_session_get_state(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CPLP_FFI_H */
